apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: h49s6f2d7-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-e2ae3c48dd.62h6.p3.openshiftapps.com/rhtap/rhtap-qe-java-quarkus:b1cf6f7e54864793b5de521bbbf0c5c58b8481bc@sha256:38d612b0ae3ef79e0871935d34bf1ddd7563c3019e8e51693cfa3641b6936742
        name: container-image  
